- name: Directories are created
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"
  tags: [confd]


- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"
  tags: [confd]


- name: Run nginx service
  shell: "docker run -d -P --name httpd1 -v {{ localhtmlfilespath }}:/usr/local/apache2/htdocs/ httpd:alpine"
